name: Update Today Times

on:
  schedule:
    - cron: "0 * * * *" # 매 정시마다 실행 (UTC 기준, 한국은 +9h)
  workflow_dispatch: # 수동 실행 가능

jobs:
  update-times:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run update_today.py
        run: python scripts/update_today.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto update times: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
